//$file${logger::src::logger.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: logger.qm
// File:  ${logger::src::logger.c}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${logger::src::logger.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"
#include "appPubList.h"
#include "sdcard.h"
#include "tusb.h"
#include "ff.h"
#include "../inc/logger.h"
#include "../inc/logger_frame.h"
#include "fatfs_sd.h"

Q_DEFINE_THIS_MODULE("logger.c")

#define CONFIG_LOGGER_AO_PRIO              (2)
#define CONFIG_LOGGER_AO_EVENT_QUEUE_LEN   (10)
#define CONFIG_LOGGER_AO_STACK             (512)
#define CONFIG_LOGGER_TICK_INTERVAL_MS     (10)
#define CONFIG_SDCARD_TICK_INTERVAL_MS     (10)

#define INDEX_FILE_PATH                    "logs/index.bin"

enum loggerSignal {
    LOGGER_TICK_SIG = MAX_PUB_SIG,
    SDCARD_TICK_SIG,
    CREATE_LOGFILE_SIG,
    START_LOGGING_SIG,
    CAN_RECEIVE_SIG,
    ERROR_SIG,
};

enum loggerTraceRecord {
    LOGGER_DEBUG_RECORD = QS_USER,
};

const uint8_t DLC_TO_BYTES[16] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 12,
                    16, 20, 24, 32, 48, 64};

//$declare${logger::sdcard::sdcard} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${logger::sdcard::sdcard} ..................................................
typedef struct {
// protected:
    QHsm super;

// private:
    QActive * parent_ao;

// public:
    uint32_t tick;
} sdcard;

// protected:
static QState sdcard_initial(sdcard * const me, void const * const par);
static QState sdcard_TOP(sdcard * const me, QEvt const * const e);
static QState sdcard_NOT_PRESENT(sdcard * const me, QEvt const * const e);
static QState sdcard_INSERTED(sdcard * const me, QEvt const * const e);
//$enddecl${logger::sdcard::sdcard} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$declare${logger::logger} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${logger::logger} ..........................................................
typedef struct {
// protected:
    QActive super;

// private:
    QHsm * sdcard;
    QTimeEvt tickEvt;

// public:
    QTimeEvt sdTickEvt;

// private:
    uint32_t tick;
    FIL file;
    uint32_t file_index;
    char logFilePath[64];
    bool logFileOpen;
} logger;

// protected:
static QState logger_initial(logger * const me, void const * const par);
static QState logger_TOP(logger * const me, QEvt const * const e);
static QState logger_INITIALIZING(logger * const me, QEvt const * const e);
static QState logger_LOGGING_MODE(logger * const me, QEvt const * const e);
static QState logger_LOGGING_INITIALIZING(logger * const me, QEvt const * const e);
static QState logger_INIT_FILESYSTEM(logger * const me, QEvt const * const e);
static QState logger_CREATE_LOG_FILE(logger * const me, QEvt const * const e);
static QState logger_LOGGING_ACTIVE(logger * const me, QEvt const * const e);
static QState logger_USB_MSC_MODE(logger * const me, QEvt const * const e);
static QState logger_ERROR(logger * const me, QEvt const * const e);
//$enddecl${logger::logger} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/*
 * Local object
 */
static sdcard l_sdcard;
static logger l_logger;
static QEvt const * l_loggerQSto[CONFIG_LOGGER_AO_EVENT_QUEUE_LEN];
static StackType_t loggerStack[CONFIG_LOGGER_AO_STACK];

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${logger::AO_logger} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${logger::AO_logger} .......................................................
QActive * const AO_logger = &(l_logger.super);
//$enddef${logger::AO_logger} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${logger::can_one_rx_callback} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${logger::can_one_rx_callback} .............................................
static void can_one_rx_callback(
    void * obj,
    CAN_RX_T * pPacket)
{
    if((obj != NULL) && (pPacket != NULL)) {
        logger * const me = (logger *)obj;
        const uint8_t channel = 0; // CAN1
        const bool isTx = false; // receive
        const bool isCanFd = (pPacket->header.FDFormat == FDCAN_FD_CAN) ? true : false;
        const uint32_t msgId = pPacket->header.Identifier;
        const uint8_t dlc = DLC_TO_BYTES[pPacket->header.DataLength];

        WriteLogEvt * pEvt = Q_NEW(WriteLogEvt, CAN_RECEIVE_SIG);
        pEvt->bufLen = FRAME_format_can(channel, isTx, isCanFd,
                           pEvt->buff, MAX_FRAME_LEN, msgId, dlc,
                           pPacket->data);
        QACTIVE_POST((QActive *)me, (QEvt *)pEvt, me);
    }
}
//$enddef${logger::can_one_rx_callback} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${logger::sdcard::sdcard_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${logger::sdcard::sdcard_ctor} .............................................
QHsm * sdcard_ctor(QActive * const parent_ao) {
    sdcard * const me = &l_sdcard;
    me->parent_ao = parent_ao;

    QHsm_ctor(&me->super, Q_STATE_CAST(&sdcard_initial));
    return (QHsm *)me;
}
//$enddef${logger::sdcard::sdcard_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${logger::LOGGER_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${logger::LOGGER_ctor} .....................................................
bool LOGGER_ctor(void) {
    static bool bInit = false;
    static const int8_t taskName[] = "LOGGER";

    if(bInit == true) {
        return true;
    }

    logger * const me = &l_logger;

    /* Call constructor */
    QActive_ctor(&me->super, Q_STATE_CAST(&logger_initial));
    me->sdcard = sdcard_ctor((QActive *)me);

    /* Create AO task */
    QActive_setAttr(AO_logger, TASK_NAME_ATTR, taskName);
    QACTIVE_START(
            AO_logger,
            CONFIG_LOGGER_AO_PRIO,
            l_loggerQSto,
            Q_DIM(l_loggerQSto),
            loggerStack,
            sizeof(loggerStack),
            (QEvt *)0
            );
    bInit = true;

    return true;
}
//$enddef${logger::LOGGER_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${logger::sdcard::sdcard} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${logger::sdcard::sdcard} ..................................................

//${logger::sdcard::sdcard::SM} ..............................................
static QState sdcard_initial(sdcard * const me, void const * const par) {
    //${logger::sdcard::sdcard::SM::initial}
    QS_OBJ_DICTIONARY(&l_sdcard);

    QS_FUN_DICTIONARY(&sdcard_TOP);
    QS_FUN_DICTIONARY(&sdcard_NOT_PRESENT);
    QS_FUN_DICTIONARY(&sdcard_INSERTED);
    return Q_TRAN(&sdcard_NOT_PRESENT);
}

//${logger::sdcard::sdcard::SM::TOP} .........................................
static QState sdcard_TOP(sdcard * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${logger::sdcard::sdcard::SM::TOP::GET_OBJECT_DICTIONARY}
        case GET_OBJECT_DICTIONARY_SIG: {
            (void)me;
            QS_OBJ_DICTIONARY(&l_sdcard);
            status_ = Q_HANDLED();
            break;
        }
        //${logger::sdcard::sdcard::SM::TOP::GET_FUNC_DICTIONARY}
        case GET_FUNC_DICTIONARY_SIG: {
            (void)me;
            QS_FUN_DICTIONARY(&sdcard_initial);
            QS_FUN_DICTIONARY(&sdcard_TOP);
            QS_FUN_DICTIONARY(&sdcard_NOT_PRESENT);
            QS_FUN_DICTIONARY(&sdcard_INSERTED);
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${logger::sdcard::sdcard::SM::TOP::NOT_PRESENT} ............................
static QState sdcard_NOT_PRESENT(sdcard * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${logger::sdcard::sdcard::SM::TOP::NOT_PRESENT}
        case Q_ENTRY_SIG: {
            me->tick = 0U;
            status_ = Q_HANDLED();
            break;
        }
        //${logger::sdcard::sdcard::SM::TOP::NOT_PRESENT::SDCARD_TICK}
        case SDCARD_TICK_SIG: {
            me->tick += CONFIG_SDCARD_TICK_INTERVAL_MS;
            //${logger::sdcard::sdcard::SM::TOP::NOT_PRESENT::SDCARD_TICK::[card_insert]}
            if (SDCARD_is_present() && SDCARD_ready()) {
                status_ = Q_TRAN(&sdcard_INSERTED);
            }
            //${logger::sdcard::sdcard::SM::TOP::NOT_PRESENT::SDCARD_TICK::[else]}
            else {
                status_ = Q_HANDLED();
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&sdcard_TOP);
            break;
        }
    }
    return status_;
}

//${logger::sdcard::sdcard::SM::TOP::INSERTED} ...............................
static QState sdcard_INSERTED(sdcard * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${logger::sdcard::sdcard::SM::TOP::INSERTED}
        case Q_ENTRY_SIG: {
            me->tick = 0U;
            status_ = Q_HANDLED();
            break;
        }
        //${logger::sdcard::sdcard::SM::TOP::INSERTED::SDCARD_TICK}
        case SDCARD_TICK_SIG: {
            me->tick += CONFIG_SDCARD_TICK_INTERVAL_MS;
            //${logger::sdcard::sdcard::SM::TOP::INSERTED::SDCARD_TICK::[card_remove]}
            if (SDCARD_is_present() == false) {
                status_ = Q_TRAN(&sdcard_NOT_PRESENT);
            }
            //${logger::sdcard::sdcard::SM::TOP::INSERTED::SDCARD_TICK::[else]}
            else {
                status_ = Q_HANDLED();
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&sdcard_TOP);
            break;
        }
    }
    return status_;
}
//$enddef${logger::sdcard::sdcard} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${logger::logger} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${logger::logger} ..........................................................

//${logger::logger::SM} ......................................................
static QState logger_initial(logger * const me, void const * const par) {
    //${logger::logger::SM::initial}
    QS_OBJ_DICTIONARY(&l_logger);

    QS_FUN_DICTIONARY(&logger_initial);
    QS_FUN_DICTIONARY(&logger_TOP);
    QS_FUN_DICTIONARY(&logger_INITIALIZING);
    QS_FUN_DICTIONARY(&logger_LOGGING_MODE);
    QS_FUN_DICTIONARY(&logger_LOGGING_INITIALIZING);
    QS_FUN_DICTIONARY(&logger_INIT_FILESYSTEM);
    QS_FUN_DICTIONARY(&logger_CREATE_LOG_FILE);
    QS_FUN_DICTIONARY(&logger_LOGGING_ACTIVE);
    QS_FUN_DICTIONARY(&logger_USB_MSC_MODE);

    me->logFileOpen = false;
    memset(me->logFilePath, 0, sizeof(me->logFilePath));

    QTimeEvt_ctorX(&me->tickEvt, &me->super, LOGGER_TICK_SIG, 0U);
    QTimeEvt_ctorX(&me->sdTickEvt, &me->super, SDCARD_TICK_SIG, 0U);

    /* Inital transition of component */
    QHSM_INIT(me->sdcard, (QEvt*)0, 0);
    return Q_TRAN(&logger_TOP);
}

//${logger::logger::SM::TOP} .................................................
static QState logger_TOP(logger * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${logger::logger::SM::TOP}
        case Q_ENTRY_SIG: {
            /* arm periodic tick timer */
            QTimeEvt_armX(&me->tickEvt, CONFIG_LOGGER_TICK_INTERVAL_MS, CONFIG_LOGGER_TICK_INTERVAL_MS);
            QTimeEvt_armX(&me->sdTickEvt, CONFIG_SDCARD_TICK_INTERVAL_MS, CONFIG_SDCARD_TICK_INTERVAL_MS);
            me->tick = 0;
            status_ = Q_HANDLED();
            break;
        }
        //${logger::logger::SM::TOP::initial}
        case Q_INIT_SIG: {
            status_ = Q_TRAN(&logger_INITIALIZING);
            break;
        }
        //${logger::logger::SM::TOP::GET_OBJECT_DICTIONARY}
        case GET_OBJECT_DICTIONARY_SIG: {
            (void)me;
            QS_OBJ_DICTIONARY(&l_logger);
            QHSM_DISPATCH(me->sdcard, e, 0);
            status_ = Q_HANDLED();
            break;
        }
        //${logger::logger::SM::TOP::GET_FUNC_DICTIONARY}
        case GET_FUNC_DICTIONARY_SIG: {
            (void)me;
            QS_FUN_DICTIONARY(&logger_initial);
            QS_FUN_DICTIONARY(&logger_TOP);
            QS_FUN_DICTIONARY(&logger_INITIALIZING);
            QS_FUN_DICTIONARY(&logger_LOGGING_MODE);

            QHSM_DISPATCH(me->sdcard, e, 0);
            status_ = Q_HANDLED();
            break;
        }
        //${logger::logger::SM::TOP::GET_SIGNAL_DICTIONARY}
        case GET_SIGNAL_DICTIONARY_SIG: {
            QHSM_DISPATCH(me->sdcard, e, 0);
            status_ = Q_HANDLED();
            break;
        }
        //${logger::logger::SM::TOP::SDCARD_TICK}
        case SDCARD_TICK_SIG: {
            QHSM_DISPATCH(me->sdcard, e, 0);
            status_ = Q_HANDLED();
            break;
        }
        //${logger::logger::SM::TOP::ERROR}
        case ERROR_SIG: {
            status_ = Q_TRAN(&logger_ERROR);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${logger::logger::SM::TOP::INITIALIZING} ...................................
static QState logger_INITIALIZING(logger * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${logger::logger::SM::TOP::INITIALIZING}
        case Q_ENTRY_SIG: {
            me->tick = 0U;
            status_ = Q_HANDLED();
            break;
        }
        //${logger::logger::SM::TOP::INITIALIZING::LOGGER_TICK}
        case LOGGER_TICK_SIG: {
            me->tick += CONFIG_LOGGER_TICK_INTERVAL_MS;
            //${logger::logger::SM::TOP::INITIALIZING::LOGGER_TICK::[sd_ready]}
            if (SDCARD_InitDone() && SDCARD_ready()) {
                status_ = Q_TRAN(&logger_INIT_FILESYSTEM);
            }
            //${logger::logger::SM::TOP::INITIALIZING::LOGGER_TICK::[else]}
            else {
                status_ = Q_HANDLED();
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&logger_TOP);
            break;
        }
    }
    return status_;
}

//${logger::logger::SM::TOP::LOGGING_MODE} ...................................
static QState logger_LOGGING_MODE(logger * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${logger::logger::SM::TOP::LOGGING_MODE}
        case Q_ENTRY_SIG: {
            me->tick = 0U;
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&logger_TOP);
            break;
        }
    }
    return status_;
}

//${logger::logger::SM::TOP::LOGGING_MODE::LOGGING_INITIALIZING} .............
static QState logger_LOGGING_INITIALIZING(logger * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${logger::logger::SM::TOP::LOGGING_MODE::LOGGING_INITIALIZING}
        case Q_ENTRY_SIG: {
            QTimeEvt_disarm(&me->tickEvt);
            QTimeEvt_disarm(&me->sdTickEvt);
            status_ = Q_HANDLED();
            break;
        }
        //${logger::logger::SM::TOP::LOGGING_MODE::LOGGING_INITIALIZING}
        case Q_EXIT_SIG: {
            QTimeEvt_armX(&me->tickEvt, CONFIG_LOGGER_TICK_INTERVAL_MS, CONFIG_LOGGER_TICK_INTERVAL_MS);
            QTimeEvt_armX(&me->sdTickEvt, CONFIG_SDCARD_TICK_INTERVAL_MS, CONFIG_SDCARD_TICK_INTERVAL_MS);
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&logger_LOGGING_MODE);
            break;
        }
    }
    return status_;
}

//${logger::logger::SM::TOP::LOGGING_MODE::LOGGING_INITIALI~::INIT_FILESYSTEM}
static QState logger_INIT_FILESYSTEM(logger * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${logger::logger::SM::TOP::LOGGING_MODE::LOGGING_INITIALI~::INIT_FILESYSTEM}
        case Q_ENTRY_SIG: {
            FRESULT res = fatfs_sd_mount();
            if(res != FR_OK) {
                QS_BEGIN_ID(LOGGER_DEBUG_RECORD, (void *)0);
                    QS_STR("mount failed!");
                QS_END();
                QEvt * pEvt = Q_NEW(QEvt, ERROR_SIG);
                QACTIVE_POST((QActive *)me, pEvt, me);
            } else {
                QS_BEGIN_ID(LOGGER_DEBUG_RECORD, (void *)0);
                    QS_STR("filesystem mounted");
                QS_END();

                /* Check "logs" directory */
                FILINFO fno;
                res = f_stat("logs", &fno);

                if (res == FR_OK) {
                    // Directory exists
                    QS_BEGIN_ID(LOGGER_DEBUG_RECORD, (void *)0);
                        QS_STR("directory found");
                    QS_END();
                    QEvt * pEvt = Q_NEW(QEvt, CREATE_LOGFILE_SIG);
                    QACTIVE_POST((QActive *)me, pEvt, me);
                } else if (res == FR_NO_FILE) {
                    // Directory does not exist, create the said directory
                    QS_BEGIN_ID(LOGGER_DEBUG_RECORD, (void *)0);
                        QS_STR("directory not found, creating...");
                    QS_END();
                    res = f_mkdir("logs");
                    if(res == FR_OK) {
                        QS_BEGIN_ID(LOGGER_DEBUG_RECORD, (void *)0);
                            QS_STR("...sucess");
                        QS_END();
                        QEvt * pEvt = Q_NEW(QEvt, CREATE_LOGFILE_SIG);
                        QACTIVE_POST((QActive *)me, pEvt, me);
                    } else {
                        QS_BEGIN_ID(LOGGER_DEBUG_RECORD, (void *)0);
                            QS_STR("...fail");
                        QS_END();
                        QEvt * pEvt = Q_NEW(QEvt, ERROR_SIG);
                        QACTIVE_POST((QActive *)me, pEvt, me);
                    }
                } else {
                    // An error occurred
                    QS_BEGIN_ID(LOGGER_DEBUG_RECORD, (void *)0);
                        QS_STR("Error: f_stat()");
                    QS_END();
                    QEvt * pEvt = Q_NEW(QEvt, ERROR_SIG);
                    QACTIVE_POST((QActive *)me, pEvt, me);
                }
            }

            status_ = Q_HANDLED();
            break;
        }
        //${logger::logger::SM::TOP::LOGGING_MODE::LOGGING_INITIALI~::INIT_FILESYSTEM::CREATE_LOGFILE}
        case CREATE_LOGFILE_SIG: {
            status_ = Q_TRAN(&logger_CREATE_LOG_FILE);
            break;
        }
        default: {
            status_ = Q_SUPER(&logger_LOGGING_INITIALIZING);
            break;
        }
    }
    return status_;
}

//${logger::logger::SM::TOP::LOGGING_MODE::LOGGING_INITIALI~::CREATE_LOG_FILE}
static QState logger_CREATE_LOG_FILE(logger * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${logger::logger::SM::TOP::LOGGING_MODE::LOGGING_INITIALI~::CREATE_LOG_FILE}
        case Q_ENTRY_SIG: {
            FRESULT res = FR_OK;
            FILINFO fno;
            bool hasError = false;

            /* Check for index.bin */
            res = f_stat(INDEX_FILE_PATH, &fno);
            if(res == FR_OK) {
                /* index.txt found */
                uint32_t index = 0;
                res = f_open(&me->file, INDEX_FILE_PATH, FA_OPEN_ALWAYS | FA_WRITE | FA_READ);
                if(res == FR_OK) {
                    UINT brw;
                    res = f_read(&me->file, &index, 4, &brw);
                    if(res != FR_OK) {
                        hasError = true;
                    } else {
                        index++;
                        me->file_index = index;
                        f_rewind(&me->file);
                        res = f_write(&me->file, &index, 4, &brw);
                        if(res != FR_OK) {
                            hasError = true;
                        }
                    }
                    f_close(&me->file);
                }
            } else if(res == FR_NO_FILE) {
                /* create index.txt */
                me->file_index = 0;
                res = f_open(&me->file, INDEX_FILE_PATH, FA_OPEN_ALWAYS | FA_WRITE);
                if(res == FR_OK) {
                    UINT bw;
                    res = f_write(&me->file, &me->file_index, 4, &bw);
                    if(res != FR_OK) {
                        hasError = true;
                    }
                    f_close(&me->file);
                }
            } else {
                /* some other error */
                hasError = true;
            }

            if(!hasError) {
                snprintf(me->logFilePath, sizeof(me->logFilePath), "logs/CanLog_%010ld.bin", me->file_index);
                QEvt * pEvt = Q_NEW(QEvt, START_LOGGING_SIG);
                QACTIVE_POST((QActive *)me, pEvt, me);
            } else {
                QEvt * pEvt = Q_NEW(QEvt, ERROR_SIG);
                QACTIVE_POST((QActive *)me, pEvt, me);
            }
            status_ = Q_HANDLED();
            break;
        }
        //${logger::logger::SM::TOP::LOGGING_MODE::LOGGING_INITIALI~::CREATE_LOG_FILE::START_LOGGING}
        case START_LOGGING_SIG: {
            status_ = Q_TRAN(&logger_LOGGING_ACTIVE);
            break;
        }
        default: {
            status_ = Q_SUPER(&logger_LOGGING_INITIALIZING);
            break;
        }
    }
    return status_;
}

//${logger::logger::SM::TOP::LOGGING_MODE::LOGGING_ACTIVE} ...................
static QState logger_LOGGING_ACTIVE(logger * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${logger::logger::SM::TOP::LOGGING_MODE::LOGGING_ACTIVE}
        case Q_ENTRY_SIG: {
            (void)BSP_CAN_register_cb(CAN_ONE, me, can_one_rx_callback);
            (void)BSP_CAN_start(CAN_ONE);

            FRESULT res = f_open(&me->file, me->logFilePath, FA_OPEN_APPEND | FA_WRITE);
            if(res != FR_OK) {
                me->logFileOpen = false;
                QS_BEGIN_ID(LOGGER_DEBUG_RECORD, (void *)0);
                    QS_STR("failed to open log file!");
                QS_END();
                QEvt * pEvt = Q_NEW(QEvt, ERROR_SIG);
                QACTIVE_POST((QActive *)me, pEvt, me);
            } else {
                me->logFileOpen = true;
                QS_BEGIN_ID(LOGGER_DEBUG_RECORD, (void *)0);
                    QS_STR(me->logFilePath);
                QS_END();
            }
            status_ = Q_HANDLED();
            break;
        }
        //${logger::logger::SM::TOP::LOGGING_MODE::LOGGING_ACTIVE}
        case Q_EXIT_SIG: {
            (void)BSP_CAN_stop(CAN_ONE);
            me->logFileOpen = false;
            f_close(&me->file);
            status_ = Q_HANDLED();
            break;
        }
        //${logger::logger::SM::TOP::LOGGING_MODE::LOGGING_ACTIVE::LOGGER_TICK}
        case LOGGER_TICK_SIG: {
            me->tick += CONFIG_LOGGER_TICK_INTERVAL_MS;
            //${logger::logger::SM::TOP::LOGGING_MODE::LOGGING_ACTIVE::LOGGER_TICK::[usb_connect]}
            if (tud_connected() && !tud_suspended()) {
                status_ = Q_TRAN(&logger_USB_MSC_MODE);
            }
            //${logger::logger::SM::TOP::LOGGING_MODE::LOGGING_ACTIVE::LOGGER_TICK::[else]}
            else {
                status_ = Q_HANDLED();
            }
            break;
        }
        //${logger::logger::SM::TOP::LOGGING_MODE::LOGGING_ACTIVE::CAN_RECEIVE}
        case CAN_RECEIVE_SIG: {
            uint32_t bw = 0;
            const FRESULT res = f_write(&me->file,
                        Q_EVT_CAST(WriteLogEvt)->buff,
                        Q_EVT_CAST(WriteLogEvt)->bufLen, (UINT*)&bw);

            if(res != FR_OK) {
                QEvt * pEvt = Q_NEW(QEvt, ERROR_SIG);
                QACTIVE_POST((QActive *)me, pEvt, me);
            }
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&logger_LOGGING_MODE);
            break;
        }
    }
    return status_;
}

//${logger::logger::SM::TOP::USB_MSC_MODE} ...................................
static QState logger_USB_MSC_MODE(logger * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${logger::logger::SM::TOP::USB_MSC_MODE}
        case Q_ENTRY_SIG: {
            me->tick = 0U;
            status_ = Q_HANDLED();
            break;
        }
        //${logger::logger::SM::TOP::USB_MSC_MODE::LOGGER_TICK}
        case LOGGER_TICK_SIG: {
            me->tick += CONFIG_LOGGER_TICK_INTERVAL_MS;
            //${logger::logger::SM::TOP::USB_MSC_MODE::LOGGER_TICK::[usb_disconnect]}
            if (tud_suspended()) {
                status_ = Q_TRAN(&logger_LOGGING_ACTIVE);
            }
            //${logger::logger::SM::TOP::USB_MSC_MODE::LOGGER_TICK::[else]}
            else {
                status_ = Q_HANDLED();
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&logger_TOP);
            break;
        }
    }
    return status_;
}

//${logger::logger::SM::TOP::ERROR} ..........................................
static QState logger_ERROR(logger * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = Q_SUPER(&logger_TOP);
            break;
        }
    }
    return status_;
}
//$enddef${logger::logger} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

