//$file${logger::inc::logger.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: logger.qm
// File:  ${logger::inc::logger.h}
//
// This code has been generated by QM 7.0.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${logger::inc::logger.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef LOGGER_H
#define LOGGER_H

#include "qpc.h"
#include "logger_frame.h"
#include "bsp_can.h"

//$declare${logger::event::WriteLogEvt} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${logger::event::WriteLogEvt} ..............................................
typedef struct {
// protected:
    QEvt super;

// public:
    uint8_t buff[MAX_FRAME_LEN];
    uint16_t bufLen;
} WriteLogEvt;
//$enddecl${logger::event::WriteLogEvt} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$declare${logger::AO_logger} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${logger::AO_logger} .......................................................
extern QActive * const AO_logger;
//$enddecl${logger::AO_logger} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$declare${logger::LOGGER_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${logger::LOGGER_ctor} .....................................................
bool LOGGER_ctor(void);
//$enddecl${logger::LOGGER_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif /* LOGGER_H */

